### ISSUE TITLE
mid 100/40 ?

### ISSUE THREAD

**Issue by antun008** [hku-mars/livox_camera_calib#1]
Can mid 100 or 40 use this algorithm for automatic calibration?

**Comment by ChongjianYUAN** [comment]
Yes, but please accumulate enough point clouds for at least 30s

**Comment by ChongjianYUAN** [comment]
> Can mid 100 or 40 use this algorithm for automatic calibration?

Yes, but please accumulate at least 30 seconds of point cloud
