### ISSUE TITLE
运行自己的数据时，出现Matrix operand is an empty matrix. in function 'checkOperandsExist'报错

### ISSUE THREAD

**Issue by ezthor** [hku-mars/livox_camera_calib#100]

**Comment by ezthor** [comment]
发错了，那个pcd是官方的，我的pcd是这个：
![image](https://github.com/hku-mars/livox_camera_calib/assets/97933067/ce631638-3f15-4894-bc49-65ad623985ea)

**Comment by HelloSZS** [comment]
请问这个应该怎么解决嘛？
