### ISSUE TITLE
论文中关于区分不平行线误匹配方法的疑惑

### ISSUE THREAD

**Issue by cchester25** [hku-mars/livox_camera_calib#102]
您好，感谢您出色的工作。在阅读该论文时，我对防止两条不平行但相近的线误匹配方法还有些不太理解，文中提到将点云边缘方向也投影至图像中并分析其与ni的正交性，我的疑惑是：点云边缘方向投影至图像中，投影后的方向向量肯定是在图像这个平面上的，那与平面的法向量也肯定是正交的呀，没有区分性。

**Comment by tdcsu** [comment]
> 您好，感谢您出色的工作。在阅读该论文时，我对防止两条不平行但相近的线误匹配方法还有些不太理解，文中提到将点云边缘方向也投影至图像中并分析其与ni的正交性，我的疑惑是：点云边缘方向投影至图像中，投影后的方向向量肯定是在图像这个平面上的，那与平面的法向量也肯定是正交的呀，没有区分性。

代码里是通过SVD分别计算点云线特征和图像线特征的方向，在设置一定的角度范围来检测两线是否平行，ni在代码中实际上是线的方向，而不是线的法线方向，因为代码中取的是最大特征值对应的特征向量
