### ISSUE TITLE
distortion mistake

### ISSUE THREAD

**Issue by AFEICHINA** [hku-mars/livox_camera_calib#12]
```
T xd = xo * distortion + (distorT[2] * xo * yo + distorT[2] * xo * yo) + distorT[3] * (r2 + xo * xo + xo * xo);
      
      
T yd = yo * distortion + distorT[2] * xo * yo + distorT[2] * xo * yo + distorT[2] * (r2 + yo * yo + yo * yo);
```

should be ?
```
T xd = xo * distortion + (distorT[2] * xo * yo + distorT[2] * xo * yo) + distorT[3] * (r2 + xo * xo + xo * xo);
      
      
T yd = yo * distortion + distorT[3] * xo * yo + distorT[3] * xo * yo + distorT[2] * (r2 + yo * yo + yo * yo);
```

**Comment by ChongjianYUAN** [comment]
> ```
> T xd = xo * distortion + (distorT[2] * xo * yo + distorT[2] * xo * yo) + distorT[3] * (r2 + xo * xo + xo * xo);
>       
>       
> T yd = yo * distortion + distorT[2] * xo * yo + distorT[2] * xo * yo + distorT[2] * (r2 + yo * yo + yo * yo);
> ```
> 
> should be ?
> 
> ```
> T xd = xo * distortion + (distorT[2] * xo * yo + distorT[2] * xo * yo) + distorT[3] * (r2 + xo * xo + xo * xo);
>       
>       
> T yd = yo * distortion + distorT[3] * xo * yo + distorT[3] * xo * yo + distorT[2] * (r2 + yo * yo + yo * yo);
> ```

Thanks for your correction and contribution. I have fixed this bug in newly commit.
