### ISSUE TITLE
demo数据的链接打不开

### ISSUE THREAD

**Issue by jhx646018057** [hku-mars/livox_camera_calib#13]
demo数据的链接打不开，能否给个百度网盘的链接

**Comment by ChongjianYUAN** [comment]
> demo数据的链接打不开，能否给个百度网盘的链接

Thanks for your suggestion. I have added the Baidu network disk link in readme.

**Comment by jhx646018057** [comment]
十分感谢您的及时回复，我还有个问题，我用的是速腾128线机械LiDAR，想采用您的方案进行和相机的联合标定，这样需要的rosbag大概录制多久的？我理解livox是非重复扫描的，机械式是重复扫描的，那我这机械LℹDAR 录制10帧是不是就可以了？

**Comment by jhx646018057** [comment]
谢谢你的回复
