### ISSUE TITLE
您好，我在视频上看到您有根据这个生成的彩色点云的三维重建，不知道您这方面的代码是否能够开源提供，我是研零的学生，想要学习一下

### ISSUE THREAD

**Issue by mytrue001** [hku-mars/livox_camera_calib#15]

**Comment by ChongjianYUAN** [comment]
请问是点云上色部分吗，点云上色部分的代码已经开源在了这个项目中

**Comment by mytrue001** [comment]
您好，可能我表述的不是很清楚，就是标定结束以后得到的彩色点云的pcd这部分该怎们获取的，冒昧问一下您是否有利用这个彩色点云进行三维重建得到mesh的开源项目吗？因为我看到好多项目还是基于图片做的，看到您这边有结合激光雷达和相机，所以想问一下，就是类似IPHONE12结合激光雷达的那种建模。

**Comment by ChongjianYUAN** [comment]
> 您好，可能我表述的不是很清楚，就是标定结束以后得到的彩色点云的pcd这部分该怎们获取的，冒昧问一下您是否有利用这个彩色点云进行三维重建得到mesh的开源项目吗？因为我看到好多项目还是基于图片做的，看到您这边有结合激光雷达和相机，所以想问一下，就是类似IPHONE12结合激光雷达的那种建模。

我暂时没有计划使用点云进行三维重建得到mesh，这是一个不错的方向，如果希望得到标定结束后彩色点云的pcd文件，可以在main函数里借助pcl库的函数将彩色点云保存成你想要的pcd文件
