### ISSUE TITLE
求解惑

### ISSUE THREAD

**Issue by mytrue001** [hku-mars/livox_camera_calib#16]
您好，请问这个如果要用自己的相机和雷达的数据如何替换呢，录制图片和点云的那个bag包，没有看懂，我刚开始学这个，所以可能问的您觉得有些简单

**Comment by ChongjianYUAN** [comment]
> 您好，请问这个如果要用自己的相机和雷达的数据如何替换呢，录制图片和点云的那个bag包，没有看懂，我刚开始学这个，所以可能问的您觉得有些简单

您好，在config_outdoor.yaml/condig_indoor.yaml里，把PointCloudTopic和ImageTopic替换成自己bag包里面点云和图片的topic名称
