### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by lijian636** [hku-mars/livox_camera_calib#17]
当我执行roslaunch livox_camera_calib calib_indoor.launch后，终端提示[ INFO] [1625557327.839229229]: Sucessfully load Point Cloud and Image
[ INFO] [1625557327.840642338]: Building Voxel
[ INFO] [1625557347.866017169]: Extracting Lidar Edge
[ INFO] [1625557352.606176671]: Load all data!
[ INFO] [1625557352.678317787]: Finish prepare!
但是等了好久还是没有变化，还是显示initial extrinsic的图片，不知道这是为什么

**Comment by ChongjianYUAN** [comment]
sorry，程序里为了方便调试加了cv::imwaitkey()，请按一下空格已继续运行程序
