### ISSUE TITLE
Question about vpnp cost function

### ISSUE THREAD

**Issue by RoseWillow** [hku-mars/livox_camera_calib#29]
Dear author, thanks for your excellent work, but I am puzzled by the vpnp cost function, I did not understand why we need the line direction to compute the matrix V, and the physical meaning of this formula V*R*V.transpose

![1636686381(1)](https://user-images.githubusercontent.com/34000284/141402218-dc522b87-8441-486f-8ee6-c4f22224690a.png)

Look forward to your reply

**Comment by ChongjianYUAN** [comment]
> Dear author, thanks for your excellent work, but I am puzzled by the vpnp cost function, I did not understand why we need the line direction to compute the matrix V, and the physical meaning of this formula V_R_V.transpose
> 
> ![1636686381(1)](https://user-images.githubusercontent.com/34000284/141402218-dc522b87-8441-486f-8ee6-c4f22224690a.png)
> 
> Look forward to your reply

![微信图片_20211116131731](https://user-images.githubusercontent.com/51600805/141925312-1301b009-3301-40bd-bc63-dba53599f5aa.png)
the line direction can help us build point-to-line residual but not point-to-point residual. Besides, the correct formulation of the point-to-line residual is shown in this picture. There are some minor bugs in the code, but they don't matter much after testing.

**Comment by RoseWillow** [comment]
Thank you for your reply, but I still don't know why you use this formula 
![e429831653a94b0876252ff9f8419ba](https://user-images.githubusercontent.com/34000284/141943592-c0e85d45-fc9c-46f8-956c-d2c602f0e8b8.png)
 to build point-to-line residuals and the physical meaning of this formula。I think we should the formula in your paper 
![87ac1a48c40c2bbf064268cd9f01ce9](https://user-images.githubusercontent.com/34000284/141943872-bceb0e50-f198-4ed5-973f-69cea730a638.png)

**Comment by ChongjianYUAN** [comment]
> Thank you for your reply, but I still don't know why you use this formula ![e429831653a94b0876252ff9f8419ba](https://user-images.githubusercontent.com/34000284/141943592-c0e85d45-fc9c-46f8-956c-d2c602f0e8b8.png) to build point-to-line residuals and the physical meaning of this formula。I think we should use the formula in your paper ![87ac1a48c40c2bbf064268cd9f01ce9](https://user-images.githubusercontent.com/34000284/141943872-bceb0e50-f198-4ed5-973f-69cea730a638.png)
> 
> What's more, I know the vector ni in the code is the direction of the line while it represent the normal vector in your paper。I do not understand why the single residual ri is a two-dimensional vector in your last reply formula.

Two-dimensional vector means the pixel difference in two dimensions. Also, you can use one dimensional residual, which means the distance in the image plane.

**Comment by tdcsu** [comment]
> Thank you for your reply, but I still don't know why you use this formula ![e429831653a94b0876252ff9f8419ba](https://user-images.githubusercontent.com/34000284/141943592-c0e85d45-fc9c-46f8-956c-d2c602f0e8b8.png) to build point-to-line residuals and the physical meaning of this formula。I think we should use the formula in your paper ![87ac1a48c40c2bbf064268cd9f01ce9](https://user-images.githubusercontent.com/34000284/141943872-bceb0e50-f198-4ed5-973f-69cea730a638.png)
> 
> What's more, I know the vector ni in the code is the direction of the line while it represent the normal vector in your paper。I do not understand why the single residual ri is a two-dimensional vector in your last reply formula.

Hi, have you understanded this block of the code, or the physical meaning of the formula V_R?
best
TD

**Comment by tdcsu** [comment]
> > Thank you for your reply, but I still don't know why you use this formula ![e429831653a94b0876252ff9f8419ba](https://user-images.githubusercontent.com/34000284/141943592-c0e85d45-fc9c-46f8-956c-d2c602f0e8b8.png) to build point-to-line residuals and the physical meaning of this formula。I think we should use the formula in your paper ![87ac1a48c40c2bbf064268cd9f01ce9](https://user-images.githubusercontent.com/34000284/141943872-bceb0e50-f198-4ed5-973f-69cea730a638.png)
> > What's more, I know the vector ni in the code is the direction of the line while it represent the normal vector in your paper。I do not understand why the single residual ri is a two-dimensional vector in your last reply formula.
> 
> Hi, have you understanded this block of the code, or the physical meaning of the formula V_R? best TD

Now it is clear.  please see the draft below：
![微信图片_20240516142943](https://github.com/hku-mars/livox_camera_calib/assets/56823449/eaa2bcd3-0ec8-4ced-b10a-5d6af8ab6094)
L_a is a lidar edge line in pixel cordinate. Point a is a lidar edge point after the undist-pinhole-tansform form lidar frame. Its corresponding image edge point b in image pixle line L_b;
it is clear that: a=pi(exp(^)L^P_i);
b=p_i;
so in the code R=(I-V)R_1 =I*R_1-V*R_1
R_1=a-b;
V=n_i.trans*n_i, ni means the direction vector of L_b
the V is a projection matrix, a vector left multiply the V therefore a vector, here is the vector <b,c> in the draft.
so here it is! 
R=(I-V)R_1 =I*R_1-V*R_1=vector<b,a>-vector<b,c>=vector<c,a>,which indicate the 3d-2d residual

note: the discription above cover the noisy situation. if no noisy, the vector<b,a> is the residual, no noisy situation is also covered in the darft when vector<b,c>=0
