### ISSUE TITLE
image query of opencv

### ISSUE THREAD

**Issue by dongdengwei** [hku-mars/livox_camera_calib#34]
在void Calibration::colorCloud函数里有以下代码：
for (size_t i = 0; i < pts_2d.size(); i++) {
    if (pts_2d[i].x >= 0 && pts_2d[i].x <= image_cols && pts_2d[i].y >= 0 &&
        pts_2d[i].y <= image_rows) {
      cv::Scalar color = rgb_img.at<cv::Vec3b>(pts_2d[i]);
      if (color[0] == 0 && color[1] == 0 && color[2] == 0) {
        continue;
      }
其中cv::Scalar color = rgb_img.at<cv::Vec3b>(pts_2d[i]);是否应改为cv::Scalar color = rgb_img.at<cv::Vec3b>(pts_2d[i].y,pts_2d[i].x),
opencv 访问数据看起来应该是这种方式

**Comment by ChongjianYUAN** [comment]
谢谢建议，最新代码中已经修改
