### ISSUE TITLE
请问您的pcd文件是如何获得的？

### ISSUE THREAD

**Issue by ailiwei17** [hku-mars/livox_camera_calib#35]
livox好像不可以直接录制pcd,如果从rosbag里读取每一帧的pcd则点云密度很低，不知道您是怎么处理的，是使用CloudCompare类的软件merge之后保存的吗？

**Comment by ChongjianYUAN** [comment]
> 

我是自己写了个代码将bag转pcd的，稍后我会把这个部分代码也更新上去

**Comment by ChongjianYUAN** [comment]
请用bag_to_pcd.launch

**Comment by ailiwei17** [comment]
谢谢
