### ISSUE TITLE
运行自己数据时无法收敛

### ISSUE THREAD

**Issue by ailiwei17** [hku-mars/livox_camera_calib#36]
我不知道如何录制覆盖图片所有位置的点云，是这种原因导致了错误吗？
或许您知道如何不改变雷达位置录制覆盖图片所有位置的点云吗
![2022-01-08 20-58-50 的屏幕截图](https://user-images.githubusercontent.com/53787807/148645191-91989dcc-cd36-4952-b067-fd7c3645ed6a.png)
![2022-01-08 20-58-50 的屏幕截图](https://user-images.githubusercontent.com/53787807/148645161-c1d81461-3e00-427e-ac0f-bea199615ca6.png)
![2022-01-08 20-59-44 的屏幕截图](https://user-images.githubusercontent.com/53787807/148645167-fdfe7038-0464-4eeb-9302-bbae68166a59.png)

**Comment by ChongjianYUAN** [comment]
> 我不知道如何录制覆盖图片所有位置的点云，是这种原因导致了错误吗？ 或许您知道如何不改变雷达位置录制覆盖图片所有位置的点云吗 ![2022-01-08 20-58-50 的屏幕截图](https://user-images.githubusercontent.com/53787807/148645191-91989dcc-cd36-4952-b067-fd7c3645ed6a.png) ![2022-01-08 20-58-50 的屏幕截图](https://user-images.githubusercontent.com/53787807/148645161-c1d81461-3e00-427e-ac0f-bea199615ca6.png) ![2022-01-08 20-59-44 的屏幕截图](https://user-images.githubusercontent.com/53787807/148645167-fdfe7038-0464-4eeb-9302-bbae68166a59.png)

请问是什么激光雷达呢，fov好像特别小

**Comment by ailiwei17** [comment]
livox mid-40

**Comment by cyn-liu** [comment]
请问使用这种范围很小的livox激光雷达，如何录制覆盖图片所有位置的点云？

**Comment by ailiwei17** [comment]
> 请问使用这种范围很小的livox激光雷达，如何录制覆盖图片所有位置的点云？

可以在比较大的场景标定

**Comment by cyn-liu** [comment]
> > 请问使用这种范围很小的livox激光雷达，如何录制覆盖图片所有位置的点云？
> 
> 可以在比较大的场景标定

你好，我没有理解你的意思，我面临的问题是激光雷达获得的点云视场范围小于图片的视场。
