### ISSUE TITLE
Running with the latestest update fail 

### ISSUE THREAD

**Issue by fuwei-li** [hku-mars/livox_camera_calib#38]
Thank you for your works, it's a great idea to solve these kind of problems.
I've run your newest code with the your indoor example , but it doesn't work.
![Screenshot from 2022-02-11 11-49-08](https://user-images.githubusercontent.com/77807894/153580634-cc888292-8cfb-4a59-9c84-c81d27c12bbf.png)
I'm pretty sure the config parameters are set to be correct. Could you please to check?

**Comment by heluoshengmu** [comment]
> problem solved.

I have the same problem. Could  you please tell me how you solved it? Thanks!
