### ISSUE TITLE
关于直线检测

### ISSUE THREAD

**Issue by Torchmm** [hku-mars/livox_camera_calib#39]
您好，感谢你的出色工作，有一个问题我想请教一下：
    从论文中看到你是用点云中提取的直线投影到图像中，然后和图像中提取的直线进行拟合。在代码中看到你是用canny来提取直线的，但是canny计算的是边缘而不是直线，那么为什么不用类似houghline这种方法来提取图像的直线呢?

**Comment by ChongjianYUAN** [comment]
> 您好，感谢你的出色工作，有一个问题我想请教一下： 从论文中看到你是用点云中提取的直线投影到图像中，然后和图像中提取的直线进行拟合。在代码中看到你是用canny来提取直线的，但是canny计算的是边缘而不是直线，那么为什么不用类似houghline这种方法来提取图像的直线呢?

您好，我是从点云中提取深度连续的边缘投影到图像中的而不是单纯的直线，因此和canny计算的边缘会有更好的重合度

**Comment by Torchmm** [comment]
好的，谢谢！
