### ISSUE TITLE
pcl problem

### ISSUE THREAD

**Issue by ailiwei17** [hku-mars/livox_camera_calib#42]
#19 
您好，我遇到了同样的问题，已经把Data.custom_msg: 1改好了，并确认了路径
![2022-03-17 21-05-00 的屏幕截图](https://user-images.githubusercontent.com/53787807/158814929-36a51996-a3df-4848-9e59-5fcb2f24896b.png)
感觉点云已经加载进去了但还是会报错
![2022-03-17 21-05-09 的屏幕截图](https://user-images.githubusercontent.com/53787807/158814937-90dd435e-32f9-4967-8894-9270f89d9327.png)

**Comment by ChongjianYUAN** [comment]
> #19 您好，我遇到了同样的问题，已经把Data.custom_msg: 1改好了，并确认了路径 ![2022-03-17 21-05-00 的屏幕截图](https://user-images.githubusercontent.com/53787807/158814929-36a51996-a3df-4848-9e59-5fcb2f24896b.png) 感觉点云已经加载进去了但还是会报错 ![2022-03-17 21-05-09 的屏幕截图](https://user-images.githubusercontent.com/53787807/158814937-90dd435e-32f9-4967-8894-9270f89d9327.png)

看上去雷达提取的edge并没有成功投影到相机平面上，可以看一下initial extrinsic对应的投影图像吗，另外这个室内场景选择的并不好，有效的边缘很少

**Comment by ailiwei17** [comment]
> > #19 您好，我遇到了同样的问题，已经把Data.custom_msg: 1改好了，并确认了路径 ![2022-03-17 21-05-00 的屏幕截图](https://user-images.githubusercontent.com/53787807/158814929-36a51996-a3df-4848-9e59-5fcb2f24896b.png) 感觉点云已经加载进去了但还是会报错 ![2022-03-17 21-05-09 的屏幕截图](https://user-images.githubusercontent.com/53787807/158814937-90dd435e-32f9-4967-8894-9270f89d9327.png)
> 
> 看上去雷达提取的edge并没有成功投影到相机平面上，可以看一下initial extrinsic对应的投影图像吗，另外这个室内场景选择的并不好，有效的边缘很少
initial [extrinsic对应的投影图像指的是这一幅图吗？好像确实没有点云的样子，我的初始的外参矩阵是使用[https://github.com/Livox-SDK/livox_camera_lidar_calibration](url)得到的，投影验证时发现不够准确，但应该不会偏差太大
![2022-03-19 10-19-43 的屏幕截图](https://user-images.githubusercontent.com/53787807/159103062-27a0bae7-30a7-41ab-9516-be1743731d5e.png)

**Comment by HungryBen** [comment]
您好，您的点云数据是如何积累的呢？

**Comment by ChongjianYUAN** [comment]
> 您好，您的点云数据是如何积累的呢？

我是直接使用livox官方给的[livox_ros_driver](https://github.com/Livox-SDK/livox_ros_driver)录制了一段静止的数据

**Comment by ChongjianYUAN** [comment]
> > > #19 您好，我遇到了同样的问题，已经把Data.custom_msg: 1改好了，并确认了路径 ![2022-03-17 21-05-00 的屏幕截图](https://user-images.githubusercontent.com/53787807/158814929-36a51996-a3df-4848-9e59-5fcb2f24896b.png) 感觉点云已经加载进去了但还是会报错 ![2022-03-17 21-05-09 的屏幕截图](https://user-images.githubusercontent.com/53787807/158814937-90dd435e-32f9-4967-8894-9270f89d9327.png)
> > 
> > 
> > 看上去雷达提取的edge并没有成功投影到相机平面上，可以看一下initial extrinsic对应的投影图像吗，另外这个室内场景选择的并不好，有效的边缘很少
> 
> initial extrinsic对应的投影图像指的是这一幅图吗？好像确实没有点云的样子，我的初始的外参矩阵是使用[https://github.com/Livox-SDK/livox_camera_lidar_calibration](url)得到的，投影验证时发现不够准确，但应该不会偏差太大。后来我也修改为默认的外参矩阵，依然没有点云 ![2022-03-19 10-19-43 的屏幕截图](https://user-images.githubusercontent.com/53787807/159103062-27a0bae7-30a7-41ab-9516-be1743731d5e.png)

请再确认下相机参数是否修改成你的设备的参数

**Comment by ailiwei17** [comment]
> > > > #19 您好，我遇到了同样的问题，已经把Data.custom_msg: 1改好了，并确认了路径 ![2022-03-17 21-05-00 的屏幕截图](https://user-images.githubusercontent.com/53787807/158814929-36a51996-a3df-4848-9e59-5fcb2f24896b.png) 感觉点云已经加载进去了但还是会报错 ![2022-03-17 21-05-09 的屏幕截图](https://user-images.githubusercontent.com/53787807/158814937-90dd435e-32f9-4967-8894-9270f89d9327.png)
> > > 
> > > 
> > > 看上去雷达提取的edge并没有成功投影到相机平面上，可以看一下initial extrinsic对应的投影图像吗，另外这个室内场景选择的并不好，有效的边缘很少
> > 
> > 
> > initial extrinsic对应的投影图像指的是这一幅图吗？好像确实没有点云的样子，我的初始的外参矩阵是使用[https://github.com/Livox-SDK/livox_camera_lidar_calibration](url)得到的，投影验证时发现不够准确，但应该不会偏差太大。后来我也修改为默认的外参矩阵，依然没有点云 ![2022-03-19 10-19-43 的屏幕截图](https://user-images.githubusercontent.com/53787807/159103062-27a0bae7-30a7-41ab-9516-be1743731d5e.png)
> 
> 请再确认下相机参数是否修改成你的设备的参数

不好意思，是我疏忽了，似乎是因为原厂给的相机的内参矩阵只是1080P的，我拍照设置为720P，导致了错误。谢谢！
