### ISSUE TITLE
FileStorage error

### ISSUE THREAD

**Issue by onionysy** [hku-mars/livox_camera_calib#45]
我在自己的数据中运行程序出现节点错误，但并没有报出具体的错误。
![图片](https://user-images.githubusercontent.com/55376216/163197903-b84d17c1-48f2-47cf-835c-71935ce0948a.png)
所以我在不同地方添加输出消息，定位到出错的位置（lidar_camera_calib/loadCalibConfig）。
![图片](https://user-images.githubusercontent.com/55376216/163198270-72fcf795-267e-41ea-9d6c-42d4409c532e.png)
运行消息显示，在fSettings初始化时就出现了错误。我们之前通过相类似的读取方式，是可以读取标定文件的。我也在网上查找相关问题，并没找到有效的答案。
不知道您是否能给出建设性的意见？感谢您的回复。

**Comment by onionysy** [comment]
我将此处标定参数直接写死解决了这个问题，但是在自己数据集上运行过程中，在“seg.segment(*inliers, *coefficients);”时ros节点直接死掉了。您那里能针对我这边的问题给出一定的意见吗，谢谢您。
![2022-04-18 14-32-27屏幕截图](https://user-images.githubusercontent.com/55376216/163766100-7c4cd80d-8770-4916-964d-00e5b84d2147.png)
![2022-04-18 14-33-06屏幕截图](https://user-images.githubusercontent.com/55376216/163766099-47cef83f-1fb9-4897-b0cd-782e5da3543f.png)
![2022-04-18 14-33-06屏幕截图](https://user-images.githubusercontent.com/55376216/163766107-a031bdf0-a67a-420a-b18c-c1ce26ca42bc.png)

**Comment by onionysy** [comment]
我将此处标定参数直接写死解决了这个问题，但是在自己数据集上运行过程中，在“seg.segment(*inliers, *coefficients);”时ros节点直接死掉了。您那里能针对我这边的问题给出一定的意见吗，谢谢您。
![2022-04-18 14-32-27屏幕截图](https://user-images.githubusercontent.com/55376216/163766100-7c4cd80d-8770-4916-964d-00e5b84d2147.png)
![2022-04-18 14-33-06屏幕截图](https://user-images.githubusercontent.com/55376216/163766099-47cef83f-1fb9-4897-b0cd-782e5da3543f.png)
![2022-04-18 14-33-06屏幕截图](https://user-images.githubusercontent.com/55376216/163766107-a031bdf0-a67a-420a-b18c-c1ce26ca42bc.png)

**Comment by ChongjianYUAN** [comment]
> 我将此处标定参数直接写死解决了这个问题，但是在自己数据集上运行过程中，在“seg.segment(*inliers, *coefficients);”时ros节点直接死掉了。您那里能针对我这边的问题给出一定的意见吗，谢谢您。 ![2022-04-18 14-32-27屏幕截图](https://user-images.githubusercontent.com/55376216/163766100-7c4cd80d-8770-4916-964d-00e5b84d2147.png) ![2022-04-18 14-33-06屏幕截图](https://user-images.githubusercontent.com/55376216/163766099-47cef83f-1fb9-4897-b0cd-782e5da3543f.png) ![2022-04-18 14-33-06屏幕截图](https://user-images.githubusercontent.com/55376216/163766107-a031bdf0-a67a-420a-b18c-c1ce26ca42bc.png)

你好，请问这个pcl版本是多少呢，我在1.7和1.9上测试过都是没问题的

**Comment by onionysy** [comment]
我这里使用的是pcl1.8版本，是必须要使用1.7或者1.9才可以吗？同时，我这里也打印了ransac_dis_thre，是有值的0.02。
![图片](https://user-images.githubusercontent.com/55376216/163818869-b8333be9-57ac-4845-973b-acafd0d2859e.png)


> > 我将此处标定参数直接写死解决了这个问题，但是在自己数据集上运行过程中，在“seg.segment(*inliers, *coefficients);”时ros节点直接死掉了。您那里能针对我这边的问题给出一定的意见吗，谢谢您。 ![2022-04-18 14-32-27屏幕截图](https://user-images.githubusercontent.com/55376216/163766100-7c4cd80d-8770-4916-964d-00e5b84d2147.png) ![2022-04-18 14-33-06屏幕截图](https://user-images.githubusercontent.com/55376216/163766099-47cef83f-1fb9-4897-b0cd-782e5da3543f.png) ![2022-04-18 14-33-06屏幕截图](https://user-images.githubusercontent.com/55376216/163766107-a031bdf0-a67a-420a-b18c-c1ce26ca42bc.png)
> 
> 你好，请问这个pcl版本是多少呢，我在1.7和1.9上测试过都是没问题的；同时，可以打印下ransac_dis_thre是否有值

我使用的pcl1.8，这是需要将pcl版本改为1.7或者1.9才可以吗？同时，我也打印了ransac_dis_thre，其值为0.02。
![图片](https://user-images.githubusercontent.com/55376216/163818985-0f534ecb-6699-4cf5-8c84-c0932350b870.png)

**Comment by ChongjianYUAN** [comment]
> 

可以试下更改pcl版本

**Comment by ChongjianYUAN** [comment]
> 我这里使用的是pcl1.8版本，是必须要使用1.7或者1.9才可以吗？同时，我这里也打印了ransac_dis_thre，是有值的0.02。 ![图片](https://user-images.githubusercontent.com/55376216/163818869-b8333be9-57ac-4845-973b-acafd0d2859e.png)
> 
> > > 我将此处标定参数直接写死解决了这个问题，但是在自己数据集上运行过程中，在“seg.segment(*inliers, *coefficients);”时ros节点直接死掉了。您那里能针对我这边的问题给出一定的意见吗，谢谢您。 ![2022-04-18 14-32-27屏幕截图](https://user-images.githubusercontent.com/55376216/163766100-7c4cd80d-8770-4916-964d-00e5b84d2147.png) ![2022-04-18 14-33-06屏幕截图](https://user-images.githubusercontent.com/55376216/163766099-47cef83f-1fb9-4897-b0cd-782e5da3543f.png) ![2022-04-18 14-33-06屏幕截图](https://user-images.githubusercontent.com/55376216/163766107-a031bdf0-a67a-420a-b18c-c1ce26ca42bc.png)
> > 
> > 
> > 你好，请问这个pcl版本是多少呢，我在1.7和1.9上测试过都是没问题的；同时，可以打印下ransac_dis_thre是否有值
> 
> 我使用的pcl1.8，这是需要将pcl版本改为1.7或者1.9才可以吗？同时，我也打印了ransac_dis_thre，其值为0.02。 ![图片](https://user-images.githubusercontent.com/55376216/163818985-0f534ecb-6699-4cf5-8c84-c0932350b870.png)

可以试下更改pcl版本
