### ISSUE TITLE
The flag of using use_rough_calib

### ISSUE THREAD

**Issue by sunwell1994** [hku-mars/livox_camera_calib#47]
Thanks for your impressive work. It works on my setup Livox mid70 + Realsense L515 when use_rough_calib is True with the default initial extrinsic matrix. However, I still have some questions.

1. Most edges match well. But the edges have some offset at the boundary of the field of view. Is it due to the distortion of the camera? I have used the dist_coeffs from the Realsense API. How do you retrieve the dist_coeffs? Maybe the given coeffs from Realsense are not accurate. 

2. Is there any benefit to setting use_rough_calib as False with a better initial extrinsic matrix? I have done several trials. When I use the default initial extrinsic matrix, the final calibration just has obvious offsets. when I use a better initial extrinsic matrix, the calibration drifts out of the image in the optimization stage, i.e no points in the image anymore. 

Thanks for your help in advance.

**Comment by ChongjianYUAN** [comment]
> Thanks for your impressive work. It works on my setup Livox mid70 + Realsense L515 when use_rough_calib is True with the default initial extrinsic matrix. However, I still have some questions.
> 
> 1. Most edges match well. But the edges have some offset at the boundary of the field of view. Is it due to the distortion of the camera? I have used the dist_coeffs from the Realsense API. How do you retrieve the dist_coeffs? Maybe the given coeffs from Realsense are not accurate.
> 2. Is there any benefit to setting use_rough_calib as False with a better initial extrinsic matrix? I have done several trials. When I use the default initial extrinsic matrix, the final calibration just has obvious offsets. when I use a better initial extrinsic matrix, the calibration drifts out of the image in the optimization stage, i.e no points in the image anymore.
> 
> Thanks for your help in advance.

1. In my experience, the phenomenon is mainly caused by distortion. Maybe you need to do distortion correction to get a more accurate dist_coeffs.
2. In some cases, setting use_rough_calib as false can save some time. For more accurate calibration, I recommend using multi_calib with use_rough_calib as true.
