### ISSUE TITLE
Rough Optimization looks good, then Optimization goes bad

### ISSUE THREAD

**Issue by pauldeee** [hku-mars/livox_camera_calib#48]
Hi there,

Cool package, hoping to get this to work! I'm using an os1-64. When I launch the calib the Rough Optimization starts and is pretty good. However, when it moves onto the Optimization step, the point cloud is aligned very poorly. It seems when Optimization starts the cloud is rotated by some amount, maybe 90 degrees.

Here are a couple photos. Please note that my camera images do not fit on my monitor so I can only show what I can see:

Rough Optimization step:
![image](https://user-images.githubusercontent.com/52274662/167240721-38d28e6b-486c-448c-96ce-77bbf8084cdf.png)

Optimization Step:
![image](https://user-images.githubusercontent.com/52274662/167240751-e80720b2-e9ed-4ed7-92b1-e161c8a74536.png)

Any thoughts or ideas would be appreciated. Thank you

**Comment by ChongjianYUAN** [comment]
> Hi there,
> 
> Cool package, hoping to get this to work! I'm using an os1-64. When I launch the calib the Rough Optimization starts and is pretty good. However, when it moves onto the Optimization step, the point cloud is aligned very poorly. It seems when Optimization starts the cloud is rotated by some amount, maybe 90 degrees.
> 
> Here are a couple photos. Please note that my camera images do not fit on my monitor so I can only show what I can see:
> 
> Rough Optimization step: ![image](https://user-images.githubusercontent.com/52274662/167240721-38d28e6b-486c-448c-96ce-77bbf8084cdf.png)
> 
> Optimization Step: ![image](https://user-images.githubusercontent.com/52274662/167240751-e80720b2-e9ed-4ed7-92b1-e161c8a74536.png)
> 
> Any thoughts or ideas would be appreciated. Thank you



> Hi there,
> 
> Cool package, hoping to get this to work! I'm using an os1-64. When I launch the calib the Rough Optimization starts and is pretty good. However, when it moves onto the Optimization step, the point cloud is aligned very poorly. It seems when Optimization starts the cloud is rotated by some amount, maybe 90 degrees.
> 
> Here are a couple photos. Please note that my camera images do not fit on my monitor so I can only show what I can see:
> 
> Rough Optimization step: ![image](https://user-images.githubusercontent.com/52274662/167240721-38d28e6b-486c-448c-96ce-77bbf8084cdf.png)
> 
> Optimization Step: ![image](https://user-images.githubusercontent.com/52274662/167240751-e80720b2-e9ed-4ed7-92b1-e161c8a74536.png)
> 
> Any thoughts or ideas would be appreciated. Thank you

Is it the wrong projection from the beginning of optimization, or during optimization?

**Comment by pauldeee** [comment]
> Is it the wrong projection from the beginning of optimization, or during optimization?

It is from the beginning of the optimization step.

**Comment by ChongjianYUAN** [comment]
> > Is it the wrong projection from the beginning of optimization, or during optimization?
> 
> It is from the beginning of the optimization step.

could you share me the dataset by email ycj1@connect.hku.hk

**Comment by sunwell1994** [comment]
I have the same issue. The rough optimization stage looks better but the optimization stage makes the alignment drift away.

**Comment by seajayshore** [comment]
For some setups we have a similar issue - rough optimisation works nicely, then fine optimisation drifts away after a while.

Did you find the solution to your version of this problem? Can you maybe share publicly if so?

**Comment by sunwell1994** [comment]
> For some setups we have a similar issue - rough optimisation works nicely, then fine optimisation drifts away after a while.
> 
> Did you find the solution to your version of this problem? Can you maybe share publicly if so?

If you just need to perform one-time calibration,  you can modify the library to save all the intermediate extrinsic matrics and then calibrate the rotation and translation manually.
