### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by Alexdev585** [hku-mars/livox_camera_calib#5]
What camera is used in this code?

Is there a ros driver for hikrobot MV-CE060-10UC? 

Thanks

**Comment by ChongjianYUAN** [comment]
> What camera is used in this code?
> 
> Is there a ros driver for hikrobot MV-CE060-10UC?
> 
> Thanks

We test our code on realsense-D435（1920*1080） and HIKVISISON MV-CA012-21UM(1280*1024). You can refer to the repo https://github.com/ChongjianYUAN/mvs_ros_pkg for ros driver of MVS camera.

**Comment by Alexdev585** [comment]
Ah perfect, thanks
