### ISSUE TITLE
关于vPnP的问题

### ISSUE THREAD

**Issue by codehory** [hku-mars/livox_camera_calib#50]
非常感谢您的分享，有几个问题想请教下您：

1. 下图这个公式可以解释下吗，代表什么含义？
2. 代码里构建的残差公式是依据的下图这个公式，但是比这个公式多乘了一个V.transpose()，可以解释下吗？
3. 方便的话，能否把这篇论文发我看看。地址: codehory@gmail.com

再次感谢，期待您的回复

![image](https://user-images.githubusercontent.com/53034289/167594461-5a3ff518-ac22-472b-b98f-02482ff3b837.png)

**Comment by ChongjianYUAN** [comment]
> 
你好,
1. 这个公式 n_i 表示的是相机边缘点的方向向量, 在常规pnp中左乘 (I-n_i n_i^T) 的意思是把3D-2D点对的残差投影到方向向量上, 可以理解为最小化3D点到2D直线的距离.
2. 代码里多乘了一个V.transpose()应该是当时写错了, 我测试删掉多的V.transpose()后结果并没有提升,因此就没有再做修改了.
3. 这个公式是我当时写的手稿,并不出自于某篇论文, 所以抱歉并没有相关的论文可以分享给你.
