### ISSUE TITLE
关于协方差矩阵的问题

### ISSUE THREAD

**Issue by LiShuaixin** [hku-mars/livox_camera_calib#51]
感谢分享，这是一个非常优秀的工作。有个问题想跟您探讨一下：在论文中对点云和图像观测量的误差的协方差进行了深入的推导，并在进行非线性优化计算时将协方差矩阵的作用引入其中，以凸显最佳观测在优化迭代中的作用。在代码中，`calCovariance`函数实现了对协方差矩阵的计算，在residual计算时也调用了该函数，但协方差的计算结果并未使用。在标定部分利用ceres实现非线性优化也没有调用残差计算函数。所以想请教一下，在调用ceres进行非线性优化时是如何将协方差加入其中的？

**Comment by ChongjianYUAN** [comment]
> 感谢分享，这是一个非常优秀的工作。有个问题想跟您探讨一下：在论文中对点云和图像观测量的误差的协方差进行了深入的推导，并在进行非线性优化计算时将协方差矩阵的作用引入其中，以凸显最佳观测在优化迭代中的作用。在代码中，`calCovariance`函数实现了对协方差矩阵的计算，在residual计算时也调用了该函数，但协方差的计算结果并未使用。在标定部分利用ceres实现非线性优化也没有调用残差计算函数。所以想请教一下，在调用ceres进行非线性优化时是如何将协方差加入其中的？

不好意思最近较忙回复较慢，代码里面得协方差计算主要是为了计算外参的不确定度的，如果是要在调用ceres进行非线性优化时加入协方差，需要改一下ceres传参，协方差在外部计算好后传到cost function里，残差项则变为r_i \sigma r_i^T
