### ISSUE TITLE
标定结果

### ISSUE THREAD

**Issue by GY-S** [hku-mars/livox_camera_calib#53]
您好，我运行了您的算法，得到了标定结果，里面包含一个4x4的矩阵和一个1x6的向量，如图：
![2022-05-31 16-33-19屏幕截图](https://user-images.githubusercontent.com/59004685/171129735-e1c2b71b-7460-4594-bac9-60cdd7838b4d.png)

请问，它们都代表什么参数？该怎么使用它们？
谢谢！

**Comment by ChongjianYUAN** [comment]
> 您好，我运行了您的算法，得到了标定结果，里面包含一个4x4的矩阵和一个1x6的向量，如图： ![2022-05-31 16-33-19屏幕截图](https://user-images.githubusercontent.com/59004685/171129735-e1c2b71b-7460-4594-bac9-60cdd7838b4d.png)
> 
> 请问，它们都代表什么参数？该怎么使用它们？ 谢谢！

最新的版本里标定结果是由雷达到相机的变换矩阵4*4，包含了外参的旋转和平移信息

**Comment by PengKunPROO** [comment]
> > 您好，我运行了您的算法，得到了标定结果，里面包含一个4x4的矩阵和一个1x6的向量，如图： ![2022-05-31 16-33-19屏幕截图](https://user-images.githubusercontent.com/59004685/171129735-e1c2b71b-7460-4594-bac9-60cdd7838b4d.png)
> > 请问，它们都代表什么参数？该怎么使用它们？ 谢谢！
> 
> 最新的版本里标定结果是由雷达到相机的变换矩阵4*4，包含了外参的旋转和平移信息

你好，雷达到相机的变换矩阵4*4，意思就是雷达在相机坐标系的位姿表示吗？也即是从雷达坐标系转到相机坐标系的变换矩阵，是这样理解吗？
