### ISSUE TITLE
请问可以提供论文的测试场景数据吗？

### ISSUE THREAD

**Issue by FengYuQ** [hku-mars/livox_camera_calib#58]
您好，我最近想用你们论文中提到的6个场景数据来进行一个对比测试，不知道方不方便可以提供一下呢？

**Comment by ChongjianYUAN** [comment]
> 您好，我最近想用你们论文中提到的6个场景数据来进行一个对比测试，不知道方不方便可以提供一下呢？

你好，可以提供一个email吗，我通过邮件发给你

**Comment by FengYuQ** [comment]
> > 您好，我最近想用你们论文中提到的6个场景数据来进行一个对比测试，不知道方不方便可以提供一下呢？
> 
> 你好，可以提供一个email吗，我通过邮件发给你

我的邮箱是：769987258@qq.com

**Comment by FengYuQ** [comment]
感谢

**Comment by fireinth** [comment]
请问可以麻烦给我也发一份吗，邮箱zhaohao_yang@126.com
