### ISSUE TITLE
calib.launch 运行出错

### ISSUE THREAD

**Issue by Tguangchao** [hku-mars/livox_camera_calib#63]
你好，感谢你的工作，我在使用的包时出现了以下错误，如果你有空，请你帮我看看，万分感谢
我的传感器套件是：Livox Avia + Realsense-D435i 
环境是 ubuntu 18.0 melodic  pcl 1.9
报了两处错误， 
![image-20220917170139911](https://user-images.githubusercontent.com/87106044/190849136-fad07c16-adc6-4194-ad82-3416684f843d.png)

**Comment by ChongjianYUAN** [comment]
> 

你好，可以附上一张可视化点云和图像吗

**Comment by Tguangchao** [comment]
rviz弹出来几秒钟，就消失了，我怀疑是pcl的问题，我正在尝试用pcl 1.7重新编译程序

**Comment by Goughhhhhh** [comment]
您好，请问您的问题解决了吗？是什么原因呢？
