### ISSUE TITLE
出结果时会一直弹框

### ISSUE THREAD

**Issue by ZyueRemi** [hku-mars/livox_camera_calib#73]
![图片](https://user-images.githubusercontent.com/98372941/205981058-72d96974-acb7-4596-8bf7-80d4ba318ed6.png)
Hi,标定后的结果总是会弹框，想问问怎么解决

**Comment by ChongjianYUAN** [comment]
> ![图片](https://user-images.githubusercontent.com/98372941/205981058-72d96974-acb7-4596-8bf7-80d4ba318ed6.png) Hi,标定后的结果总是会弹框，想问问怎么解决

把代码里的initial extrinsic显示注释掉就ok了，opencv的imshow没有进一步更新时就会显示无响应
