### ISSUE TITLE
运行时opencv报错modules/core/src/matrix_expressions.cpp:23: error: (-5:Bad argument) Matrix operand is an empty matrix. in function 'checkOperandsExist'

### ISSUE THREAD

**Issue by justleap** [hku-mars/livox_camera_calib#93]
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.2.0) ../modules/core/src/matrix_expressions.cpp:23: error: (-5:Bad argument) Matrix operand is an empty matrix. in function 'checkOperandsExist'

**Comment by zsungi** [comment]
Hi, I have the same issue, what was your solution for this problem?

**Comment by HelloSZS** [comment]
请问应该怎么解决吗
