### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by ezthor** [hku-mars/livox_camera_calib#99]
i can run the demo successfully once,but maybe after i use pip -r to install an requirement list in another anaconda environment and change the version of pcl ,i encounter this problem:
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libpcl_io.so: undefined reference to `libusb_set_option'
.Now I am using Ubuntu 20.04 and pcl version : libpcl-dev     1.10.0+dfsg-5ubuntu1
is it a problem with pcl version? which version should i use? plz help,thanks!!
![Screenshot from 2023-11-18 22-50-09](https://github.com/hku-mars/livox_camera_calib/assets/97933067/3ccccc77-02c3-4a0f-a67d-3d77f6234161)

**Comment by ezthor** [comment]
I used docker to reconfigure the environment and successfully catkin_make ,though still don't know how to fix this problem.

**Comment by WilsonGuo** [comment]
问题出现在安装了海康摄像头的配置软件，删除这个软件即可正常编译和运行程序。

分析问题：这个错误是在我安装完海康摄像头和速腾的SDK后，就出现的，所以问题大概率出现这里，然后直接全局搜索 libusb 的库文件，然后在海康的MVS下找到这个文件了，然后把MVS删除后，就可以编译了。

**Comment by TZECHIN6** [comment]
但刪掉後還能用到HIK相機嗎? 還是只需刪`libusb-x.so.x`

**Comment by ezthor** [comment]
> 问题出现在安装了海康摄像头的配置软件，删除这个软件即可正常编译和运行程序。
> 
> 分析问题：这个错误是在我安装完海康摄像头和速腾的SDK后，就出现的，所以问题大概率出现这里，然后直接全局搜索 libusb 的库文件，然后在海康的MVS下找到这个文件了，然后把MVS删除后，就可以编译了。

可能是这个原因，我也用了海康驱动，后面在docker里配置环境不需要海康驱动所以没问题

**Comment by ezthor** [comment]
> 但刪掉後還能用到HIK相機嗎? 還是只需刪`libusb-x.so.x`

这我

**Comment by ezthor** [comment]
> 但刪掉後還能用到HIK相機嗎? 還是只需刪`libusb-x.so.x`

这我不太清楚，但我建议外部环境保留MVS在docker中重新配置一个标定环境。
